### ISSUE TITLE
Stuck on Updating a package

### ISSUE THREAD

**Issue by VlaDexa** [microsoft/winget-create#142]
# Brief description of your issue
I was truing to update the Rufus package and it failed while checking the already submitted exe
# Steps to reproduce

wingetcreate.exe update Rufus.Rufus

# Expected behavior

Being able to progress further

# Actual behavior

It exits with error `Each new installer URL must have a match to an existing installer node based on installer type and architecture.`

# Environment

Windows 10 21H1
Windows Package Manager Manifest Creator version - v0.3.0.3

**Comment by ryfu-msft** [comment]
Hey @VlaDexa,

For the update command to execute successfully, we require that the user updates with a new installer URL(s) and that the number of new installer URLs must match the number of existing installer URLs in the manifest. In your case for Rufus.Rufus, you would just need a single installer URL which you can specify by including the --urls flag. Here's an example: `wingetcreate.exe update Rufus.Rufus --version <newVersion> --urls <newInstallerUrl>` . 

Regardless, there should be a better error message to convey this. Thanks for pointing this out to us!

**Comment by denelon** [comment]
@ryfu-msft when we detect a single URL or a list of URLs can we prompt for them? I think we could fairly easily handle the single URL case, but I completely understand the additional complexity of multiple URLs or "Installers". More work needs to happen to help authors understand which URLs to use in that case.
