### ISSUE TITLE
wingetcreate <manifest> -v -i does nothing

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-create#176]
Trying to run this command or anything with -v -i just fails to do anything, bringing up instead the help info and stating that "Option 'v,version' has no value"

> I dont know whats going on with this manifest and wingetcreate but I keep having to manually update it rather than just using wingetcreate update

Copied over from an [earlier PR](https://github.com/microsoft/winget-pkgs/pull/28105) that you made where you also had issues.

Hey @Masamune3210, 

I noticed you had some issues with the update command for Winget-Create. The reason for the mismatch is that the existing manifest is looking for a neutral inno installer, but we detected the installer to be an x86 inno.

Fortunately, in our latest release of Winget-Create, we added an interactive update flag for you to manually fix those mismatches by running

wingetcreate update AntibodySoftware.WizTree -v <Version> -i
We hope you try it out, and feel free to tag me or create a new GitHub issue if it doesn't behave as you expected.

Thanks!

_Originally posted by @ryfu-msft in https://github.com/microsoft/winget-pkgs/issues/28351#issuecomment-926979866_

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/134776638-4d809cdd-eb4f-4100-94b6-9575f01263b1.png)

**Comment by Masamune3210** [comment]
Not sure If I'm missing something or not, copied the command directly from the issue to make sure I typed it right and nothing

**Comment by ryfu-msft** [comment]
> Not sure If I'm missing something or not, copied the command directly from the issue to make sure I typed it right and nothing

Ah, you still need to include a version when you include the -v flag. Try again but make sure to include the version you want to update to. For example:


wingetcreate update AntibodySoftware.WizTree -v 4.03 -i

**Comment by Masamune3210** [comment]
Ok, knew I was missing something, thanks!
