### ISSUE TITLE
Items at root level are not modified

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-create#211]
### Brief description of your issue

When a product code exists at the root level and a package is updated using wingetcreate, the product code from the root level is not considered when updating the product code at the installer level

Edit: This applies to all other fields too

### Steps to reproduce

Unsure how to reproduce; Noticed in  https://github.com/microsoft/winget-pkgs/pull/37334/files#diff-b05d41986a400b8d3fc1c2f419d8e8f48290cba8ae0ce8ac5db177b44c415eb9

### Expected behavior

The product code at the root level will be either updated or removed

### Actual behavior

There are two different product codes in the manifest

### Environment

```shell
¯\_(ツ)_/¯
```

**Comment by Trenly** [comment]
Sorry for lack of repro steps; I figured that having an issue was most important, even if I wasn't sure how to reproduce

**Comment by mdanish-kh** [comment]
- Resolved in #409

The PR introduces the behavior where the fields at the root level will be moved and overwritten at the installer level before the update begins. At the end of the update, the values to be moved back to the root level if they are common between all installers. So now, you won't have a case where the ProductCode at the root level will be different from an installer level ProductCode

**Comment by mdanish-kh** [comment]
Resolved in WinGet-Create 1.5.1.0 in PR #413 and #409

cc @denelon / @Trenly  if this can be marked as completed
