### ISSUE TITLE
Application link not changed

### ISSUE THREAD

**Issue by LlFPrograms** [microsoft/winget-create#237]
### Brief description of your issue

When I **update** the application, it works but when I install it from _Winget_, it installs the _**previous version**_

### Steps to reproduce

1. _**Update**_ your application with new application files **by using this command**: _wingetcreate update <packageIdentifier> -u "https://github.com/YourUsername/yourrepository/releases/download/version/yourapp.exe|x64" --version -newversion- -t -githubPersonalAccessToken-_
2. _Install_ the new version of your application by using the **package identifier** or **it name**.
3. Execute the application
4. If a setting in your application show the current version of the application, it would show the previous version 

### Expected behavior

When you launch cmd or powershell, type (without quotes and change the sentence between dashes by the application name or it package identifier): "_winget search -YourApplicationNameOrPackageIdentifier-_" and it would shows the new version of your app in the "Version" column.

### Actual behavior

In the "Version" column, it is showing the previous version of the app and installs the previous version of the app.

### Environment

```shell
[winget --info]
Windows Package Manager 0.5.0.1
Windows: LelanceFlamer.TLFDADIDW 3.6.2
Package: LelanceFlamer.TLFDADIDW 3.6.2
```

**Comment by ryfu-msft** [comment]
I am closing this issue as I believe this issue has been resolved now that your latest version is showing up in the community repository.
