### ISSUE TITLE
`wingetcreate new` detected installertype that fails

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-create#26]
# Brief description of your issue

`wingetcreate new` detected the wrong installertype which made `winget install -m M:\pathtomanifest` fail with error code 1620
# Steps to reproduce

`wingetcreate new https://www.expressvpn.works/clients/windows/expressvpn_windows_10.2.4.11_release.exe`

`winget install -m .\e\ExpressVPN\ExpressVPN\10.2.4.11\`

# Expected behavior

For it to work

# Actual behavior

Error code 1620

# Environment

```none
Windows Package Manager Manifest Creator version? (wingetcreate.exe -?)

Any other software?
```

**Comment by palenshus** [comment]
Very strange indeed. From the exe manifest, this does seem to be a WiX installer:

```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <assemblyIdentity name="setup.exe" version="1.0.0.0" processorArchitecture="x86" type="win32"/>
    <description>WiX Toolset Bootstrapper</description>
```

However, winget fails when trying to install it as such. Changing wix to exe in the installer manifest seems to fix the issue. It's possible either this is an extremely rare edge case where the workaround of manually editing the manifest is sufficient, or it's possible there's something wrong with our installerType detection heuristic.

**Comment by OfficialEsco** [comment]
EA Desktop also does the same
`https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe`
But i do believe the EULA switch works, so it IS a wix installer, however when i have the `InstallerType: wix` and the Silent parameter /silent which "works(?)" the installer comes with a error..

I don't know how installers work, but do they disable the parms for some wild reason?

**Comment by palenshus** [comment]
Apparently, the "wix" installerType is actually for WiX MSIs. When the WiX toolset is used to create an exe, that's actually a "burn" installer. https://wixtoolset.org/documentation/manual/v3/bundle/

**Comment by OfficialEsco** [comment]
> Apparently, the "wix" installerType is actually for WiX MSIs. When the WiX toolset is used to create an exe, that's actually a "burn" installer. https://wixtoolset.org/documentation/manual/v3/bundle/

burn did indeed solve the EA Desktop InstallerType, hope there is a easy way to detect the difference between burn and WiX MSI :)

**Comment by palenshus** [comment]
We decided to just set the installerType for all MSIs as "msi" for now. Winget itself doesn't treat them differently: https://github.com/microsoft/winget-cli/blob/cf6f8e58195bf033a1a5872f7b800866cd27a586/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L348. If that ever changes, we'll re-evaluate
