### ISSUE TITLE
Installer download fails when download URLs are HTTP redirects

### ISSUE THREAD

**Issue by chausner** [microsoft/winget-create#27]
# Brief description of your issue

The tool does not process download URLs that are redirects to another URL.

# Steps to reproduce

Run `winget new` and enter URL `https://download.qt.io/official_releases/qtcreator/4.15/4.15.0/qt-creator-opensource-windows-x86_64-4.15.0.exe`

# Expected behavior

The tool should follow the redirect (but insert the original URL in the manifest).

# Actual behavior

The tool fails with error
```
Failed to download installer.
HTTP response was unsuccessful. Status code: Redirect
```

# Environment

```none
Windows Manifest Creator v0.1.0.1
```

**Comment by palenshus** [comment]
@denelon, does winget support redirect URLs? If so, we should add support in wingetcreate too

**Comment by denelon** [comment]
I would suggest testing with the client. I believe some forms of redirect are supported, but I'm not sure if they all are. I also know we had some challenges with range request issues on some HTTP servers with range requests disabled.

**Comment by palenshus** [comment]
Looks like winget doesn't currently support this either:

![image](https://user-images.githubusercontent.com/7907848/120684035-1fd03300-c453-11eb-9bee-49108231d1b5.png)

Bringing up with winget team

**Comment by ghost1372** [comment]
@denelon  If using open source projects is not a problem, this library can download the desired link without any problems
https://github.com/bezzad/Downloader
also It will also be much easier to get the download Progress, because you are using httpclient for downloading files (As far as I know) and it is not possible to get progress and it must be implemented 
https://github.com/microsoft/winget-create/blob/89ac44499876154244dc8b918cacf413758b9c2a/src/WingetCreateCore/Common/PackageParser.cs#L126

If there is no problem with this, maybe I can make a pr

**Comment by denelon** [comment]
@ghost1372 we're looking to "share" the same mechanism as the [Windows Package Manager](https://github.com/microsoft/winget-cli) so we have the same experience for users when `winget create` is a thing. We need to do some more work to improve how we handle redirects in both projects. There are still some gaps with using "wininet" vs "do" (Delivery Optimization). We also need to look at whether or not we want DO in this tool as well. I don't think that necessarily is a good idea for this tool currently, but I'd hate to have someone able to successfully download the installer to build a manifest only for it to fail the validation pipelines.

**Comment by denelon** [comment]
@ghost1372 GPL-3.0 License looks like it's permissive enough, but we have to validate several Microsoft policy and legal requirements before we could include in this codebase under MIT. The team will talk it over. We would LOVE a community contribution. We just need to make sure everything is OK to proceed here before you spend your valuable time and effort creating a PR that we might have to reject.

**Comment by ghost1372** [comment]
Thank you, I am waiting for your decisions and I will respect it in any case And whenever there is no problem, I try to participate

**Comment by denelon** [comment]
We greatly appreciate your contributions! We have quite a few processes to go through before we're able to release projects open source. I pushed the team to get this out ASAP so we could get feedback and improve.
