### ISSUE TITLE
wingetcreate 1.1.2.0 produces manifiests rejected by WinGetSvc-Validation

### ISSUE THREAD

**Issue by pedrolcl** [microsoft/winget-create#297]
### Brief description of your issue

[A PR](https://github.com/microsoft/winget-pkgs/pull/69067/files) for my updated app has been rejected because:

> Please verify the manifest file is compliant with the package manager [1.0 manifest specification](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md).

The manifest has been created with wingetcreate.exe v1.1.2.0 with this command line:

~~~
wingetcreate.exe update --urls https://sourceforge.net/projects/dmidiplayer/files/v1.7.0/dmidiplayer-1.7.0-win-x64-setup.exe/download --version 1.7.0 Drumstick.dmidiplayer
~~~

The manifests use the schema https://aka.ms/winget-manifest.installer.1.2.0.schema.json which is certainly not the 1.1 schema

### Steps to reproduce

use the latest wingetcreate.exe to update an existing manifest, and it will use an schema that will be rejected by the automatic validation when included in a merge request.

### Expected behavior

wingetcreate.exe should use a schema that is accepted by winget 

### Actual behavior

The manifests created by wingetcreate.exe are being rejected by winget

### Environment

```shell
winget --info
Administrador de paquetes de Windows v1.3.2091
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.19044.1826
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.18.2091.0
```

**Comment by Trenly** [comment]
See microsoft/winget-pkgs#68845

**Comment by denelon** [comment]
FYI, I'm aiming to open up 1.2 schema validation in the community repository tomorrow (EOD).

**Comment by denelon** [comment]
We hit a snag. It's looking more like the end of the week. We will get it out ASAP.

**Comment by ryfu-msft** [comment]
We have opened up 1.2 schema validation in the community repository. Closing this issue as it has now been resolved.
