### ISSUE TITLE
ManifestDocumentationUrl is outdated

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-create#307]
### Brief description of your issue

A URL for manifest information is hardcoded into the WingetCreate CLI and is currently outdated

### Steps to reproduce

Run `winget create new`

### Expected behavior

A link to `https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0` or similar

### Actual behavior

A link to `https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md`

### Environment

```shell
v1.1.2.0
```

**Comment by ryfu-msft** [comment]
URL should be updated with a proper aka.ms vanity url
