### ISSUE TITLE
Ask for more metadata imput during the creation of the new manifest

### ISSUE THREAD

**Issue by ppvnf** [microsoft/winget-create#332]
### Description of the new feature / enhancement

I've just created my first manifest using Winget Create. It was pretty straightforward, but I thing it should have asked for metadata imput such as:

PublisherUrl:
PublisherSupportUrl
PrivacyUrl
PackageUrl
LicenseUrl
CopyrightUrl
Moniker
Tags
ReleaseNotesUrl
PurchaseUrl

**Comment by ryfu-msft** [comment]
Hey @ppvnf, 

When you create a new manifest, the required prompts are shown first. After you finish answering all required prompts, you should see another prompt asking if you would like to add any optional fields. If you reply with 'Y', you should see all of the optional metadata fields that you are proposing above. Let me know if you have any issues getting there and I can give you a more thorough example.

**Comment by ppvnf** [comment]
Thanks. I will try that out when I create a new manifest
