### ISSUE TITLE
Failed to parse package hosted on Github

### ISSUE THREAD

**Issue by Masamune3210** [microsoft/winget-create#336]
### Brief description of your issue

Trying to add https://github.com/BakasuraRCE/abgx360/releases/download/v1.0.6-and-v1.0.2/windows_abgx360_v1.0.6_setup.exe
to the repo but wingetcreate keeps saying that it failed to parse the package

### Steps to reproduce

Try to create a manifest using https://github.com/BakasuraRCE/abgx360/releases/download/v1.0.6-and-v1.0.2/windows_abgx360_v1.0.6_setup.exe as the source

### Expected behavior

Package is downloaded and parsed correctly

### Actual behavior

Failed to parse the package from [https://github.com/BakasuraRCE/abgx360/releases/download/v1.0.6-and-v1.0.2/windows_abgx360_v1.0.6_setup.exe]

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Windows: Windows.Desktop v10.0.22621.963
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0
```

**Comment by Trenly** [comment]
I believe it is because the exe file doesn't have a manifest embedded in it (according to ResourceHacker).

Might be related to https://github.com/microsoft/winget-create/pull/334/files

**Comment by Masamune3210** [comment]
Hmm, you might be right

**Comment by ryfu-msft** [comment]
I tried this out with the new changes from #334. WingetCreate can successfully parse this package but there's no default/suggested fields since there's no manifest resource that we can use to pre-populate those fields. I am closing this issue since there's no longer a failure.
