### ISSUE TITLE
Search for duplicates

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-create#34]
# Description of the new feature/enhancement

There should be a way to search for duplicates when executing `wingetcreate new`. This may mean a dependency on the Windows Package Manager. There is also a feature in the winget-pkgs repository to evaluate SHA256 hashes and provide a warning.

# Proposed technical implementation details (optional)

Once the installer has been downloaded and parsed, several different search parameters are available like the package name the installer URL and the SHA256 hash. This may also justify other features on the Windows Package Manager client to support additional search parameters for different values.

**Comment by ryfu-msft** [comment]
Closing this as #207 is now tracking
