### ISSUE TITLE
Microsoft `https://aka.ms/winget-manifest-schema` redirects to Manifest Schema `1.2` instead of `1.4`

### ISSUE THREAD

**Issue by aisgbnok** [microsoft/winget-create#346]
### Brief description of your issue

When using the `wingetcreate` tool it provides a [`https://aka.ms/winget-manifest-schema`](https://aka.ms/winget-manifest-schema) link that directs redirects to [Manifest Schema 1.2](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0).

https://user-images.githubusercontent.com/10838153/217156982-25c8166b-5647-4d29-80f7-cd62fdc316de.mp4

### Steps to reproduce

1. Use WingetCreate to generate a new manifest.
    ```PowerShell
    wingetcreate new https://www.example.com/installer-1.0.0.exe
    ```
2. WingetCreate provides the link:
    > For information about the restrictions for each field, visit https://aka.ms/winget-manifest-schema

### Expected behavior

The [`https://aka.ms/winget-manifest-schema`](https://aka.ms/winget-manifest-schema) link should redirect to [Manifest Schema 1.4](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0).

### Actual behavior

The [`https://aka.ms/winget-manifest-schema`](https://aka.ms/winget-manifest-schema) link redirects to [Manifest Schema 1.2](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0).

### Environment

```shell
Windows Package Manager (Preview) v1.5.101-preview
Windows: Windows.Desktop v10.0.22623.1250
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.101.0
---
Windows Package Manager Manifest Creator v1.2.5.0
```

**Comment by denelon** [comment]
Thanks for reporting this. We will update the link.

**Comment by ryfu-msft** [comment]
This has been updated. Thanks for bringing this to our attention @aisgbnok !
