### ISSUE TITLE
Add the licence-url field

### ISSUE THREAD

**Issue by tiziodcaio** [microsoft/winget-create#35]
# Description of the new feature/enhancement

Add the licence-url field (and remove it when is blank) when submitting a new program

**Comment by tiziodcaio** [comment]
See #37

**Comment by ryfu-msft** [comment]
Hey @tiziodcaio,

This feature has been added in PR #106. We're aiming to have a new release soon, so we hope you'll try it out and let us know what you think. Thanks for your help and contribution!
