### ISSUE TITLE
Add ability to pass in a PR title with submit and update

### ISSUE THREAD

**Issue by edwardskrod** [microsoft/winget-create#359]
## What 
Add ability to change the automatically-generated PR title when submitting PR.

## Why
When submitting a PR with WinGetCreate update or WinGetCreate submit, the PR titles are automatically generated from the PackageIdentifier <id> and PackageVersion -v <version>
There are times when it would be nice to update the PR title with a custom PR title.

For example, Visual Studio has Preview versions that get released on a regular cadence.   Visual Studio 17.6 has 8 Preview Versions.  

Preview versions are based on the first release of the minor, i.e. 17.6.0.  

Right now, each preview version's PR in GitHub is identical:  

Microsoft.VisualStudio.2022.Community.Preview version 17.6.0

Instead, Visual Studio would like to be able to add the Preview version to the title.

- Microsoft.VisualStudio.2022.Community.Preview version 17.6.0 Preview 1
- Microsoft.VisualStudio.2022.Community.Preview version 17.6.0 Preview 2
- Microsoft.VisualStudio.2022.Community.Preview version 17.6.0 Preview 3

To do this today, we'd need to update the version from "17.6.0" to "17.6.0 Preview 1".  But this would also update the package version in the manifest, which is something we don't want to do.

Instead, we propose to allow WinGetCreate to accept a parameter to override the PR title.

### Proposed technical implementation details

wingetcreate.exe submit [\<options>] <PathToManifest> [-p \<pr title>]
wingetcreate.exe update \<id> [-u \<urls>] [-v \<version>] [-s] [-t \<token>] [-o \<output directory>] [-p \<pr title>]

Accept the PR title as a command line parameter for the submit and update commands.  Use this title rather than automagically generating the title in code from the Id and Version..

**Comment by ryfu-msft** [comment]
Fixed in PR #362
