### ISSUE TITLE
Github Token Specificity

### ISSUE THREAD

**Issue by MrHinsh** [microsoft/winget-create#374]
### Brief description of your issue

There is no definition on https://github.com/microsoft/winget-create/blob/main/doc/update.md of what specific permissions this PAT token needs?

Questions:

- Classic or Scoped?
- Which flags are need?

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-create#github-personal-access-token-permissions

According to the documentation above, a classic token with `public_repo` flag is needed for WinGetCreate

**Comment by MrHinsh** [comment]
It would be great if this could be linked directly from the documentation pages for the actions that need it.
