### ISSUE TITLE
`wingetcreate.exe` fails with `Unable to create a reference to the forked repository`

### ISSUE THREAD

**Issue by rednoah** [microsoft/winget-create#473]
### Brief description of your issue

`wingetcreate.exe` fails with the following error message:
```
Unable to create a reference to the forked repository. This can be caused when the forked repository is behind by too many commits. Sync your fork and try again.
```

Unfortunately, the error message doesn't really tell us anything. `wingetcreate.exe` presumably forks the latest package repository so the error message doesn't make sense to me. Does `wingetcreate.exe` have a `-verbose` flag?

### Steps to reproduce

I'm using the following GitHub action:
* https://github.com/filebot/plugins/blob/master/winget/make.ps1
* https://github.com/filebot/plugins/blob/master/.github/workflows/winget.yml

You can find the GitHub CI log here:
https://github.com/filebot/plugins/actions/runs/6782204951/job/18433976886

### Expected behavior

`wingetcreate.exe` should work or print a useful error message.

### Actual behavior

`wingetcreate.exe` doesn't work.

### Environment

```shell
GitHub Action `windows-latest` running the `https://aka.ms/wingetcreate/latest` executable.
```

**Comment by Trenly** [comment]
@rednoah - It looks like you're more than 90,000 commits behind master on https://github.com/rednoah/winget-pkgs. Merging in the latest commits from microsoft/winget-pkgs should resolve the issue

**Comment by rednoah** [comment]
Cheers! That was the key. I deleted my `rednoah/winget-pkgs` and now it works. Thank you very much for the help. Checking for forks in my accounts would never have occured to me.

**Comment by nett00n** [comment]
For the future users:
- Go to **your profile** on GitHub web page
- Go to your repositories
- Find there `winget-pkgs` repo
- Press the `sync fork` button there
![image](https://github.com/microsoft/winget-create/assets/1846116/8bbc98c0-a903-4d9a-9b8d-5d1e7540c265)

**Comment by mdanish-kh** [comment]
> For the future users:
> 
>     * Go to **your profile** on GitHub web page
> 
>     * Go to your repositories
> 
>     * Find there `winget-pkgs` repo
> 
>     * Press the `sync fork` button there

That's certainly an option if you're doing things manually but may not be the most suitable option if you're automating the releases in a CI/CD pipeline. You can sync the repo using `gh` CLI if you're using wingetcreate in a CI environment, I'll link a couple of examples:

- https://github.com/microsoft/devhome/blob/main/.github/workflows/winget-submission.yml#L9-L15
- https://github.com/coder/coder/blob/817cc78b948216a1ec005a352cf0301b4510092c/.github/workflows/release.yaml#L410-L414
