### ISSUE TITLE
Add support for arguments in manifest

### ISSUE THREAD

**Issue by josh-65** [microsoft/winget-create#51]
# Description of the new feature/enhancement
Oculus and some other programs need a / argument to run silent mode. This can not be done with winget right now

# Proposed technical implementation details (optional)
When using the wingetcrete the should be a argument option were i can add / commands

**Comment by OfficialEsco** [comment]
WinGet CLI and Manifest does have support for Switches. https://aka.ms/winget-manifest.installer.1.0.0.schema.json
Switches prompt will be added for `wingetcreate` once its out of its alpha stage.

**Comment by josh-65** [comment]
oh right cool i will try that.
