### ISSUE TITLE
wingetcreate does not update product code inside ARP Entries

### ISSUE THREAD

**Issue by vedantmgoyal9** [microsoft/winget-create#524]
### Brief description of your issue

Title.

### Steps to reproduce

Just take any manifest from winget-pkgs and run `winget update`.

### Expected behavior

Product Code and Upgrade Code should be updated if they are present inside `AppsAndFeaturesEntries`.

### Actual behavior

Product Code and Upgrade Code are NOT updated if they are present inside `AppsAndFeaturesEntries`.

### Environment

```shell
Latest wingetcreate version.
```

**Comment by Masamune3210** [comment]
It's not winget's job, that falls under one of the last things the program updater is supposed to change whenever it is preforming an upgrade. As you can see, an annoying amount of them do not do so correctly.

**Comment by mdanish-kh** [comment]
I think one concern may be that `AppsAndFeaturesEntries` can have multiple nodes. How would wingetcreate know which node to update? Granted we currently only take the "primary" ARP entry in the community repo, and I've handled this partially in #520 where I only update the first node that's wingetcreate sees. Might need a more precise way to handle these though
