### ISSUE TITLE
Multiple URL support

### ISSUE THREAD

**Issue by tiziodcaio** [microsoft/winget-create#53]
# Description of the new feature/enhancement

Add the possibility to add more than one installer in wingetcreate new and either wingetcreate update

# Proposed technical implementation details (optional)

~I think this is a low priority feature request, so keep calm and develop the rest 😆~
I didn't saw the source code, so I'm ignorant

**Comment by OfficialEsco** [comment]
Actually this is a pretty high priority because `wingetcreate update` doesn't work with multiple urls.
Do you have any suggestion to how we would type in the multiple urls?
I'd say `wingetcreate update --multiurl` `C:\manifests\firefox\urls.txt` or `https://github.com/microsoft/edge/urls.txt` and/or csv

**Comment by tiziodcaio** [comment]
Why don't we make interactive input like wingetcreate new???

**Comment by tiziodcaio** [comment]
Sorry but I'm not expert about doing it, I will be able to suggest some ideas for the project 😅

**Comment by OfficialEsco** [comment]
I made that in [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) and it can be very bothersome, but yes it should also ask if you would like to create another installer.
One example is Firefox can have like 500 installers 👀

**Comment by iDolmatov** [comment]
> Actually this is a pretty high priority because `wingetcreate update` doesn't work with multiple urls.
> Do you have any suggestion to how we would type in the multiple urls?
> I'd say `wingetcreate update --multiurl` `C:\manifests\firefox\urls.txt` or `https://github.com/microsoft/edge/urls.txt` and/or csv

Depends on the task.

If there are different bit depths, then why not list them separated by commas?
We request the main parameters once, and for each bit we specify "write a link for the XY" version. If switches are specified, then after the first instruction, ask the question "Use these switches for all bit sizes of distributions of this type?".


Using Firefox as an example, you still have to fill in the parameters in the form of language and product code.
Here, the option of handling variables in a link would be suitable, but you need to think in advance which characters of the "parentheses" of the variable will not conflict with PowerShell and can be easily specified for processing.
Example:
`https://download-installer.cdn.mozilla.net/pub/firefox/releases/89.0/win64/en-US/Firefox%20Setup%2089.0.msi`
convert to
`https://download-installer.cdn.mozilla.net/pub/firefox/releases/%Version%/$win64|win32|win64-aarch64$/en-US/Firefox%%20Setup%%20%version%.$exe|msi$`
Pre-questions:
Write aviable languages. Write aviable versions.

**Comment by denelon** [comment]
We were actually given the opposite feedback during an earlier discussion. The thought process was if you're going to have a file (sidecar) to pass into the tool, you might as well build the manifest. I believe that may have been perceived for the CI/CD unattended use case though. When you are in an interactive mode, it might make more sense.

**Comment by tiziodcaio** [comment]
> `https://download-installer.cdn.mozilla.net/pub/firefox/releases/%Version%/$win64|win32|win64-aarch64$/en-US/Firefox%%20Setup%%20%version%.$exe|msi$`

This would be very intersting!

**Comment by bearmannl** [comment]
> Actually this is a pretty high priority because `wingetcreate update` doesn't work with multiple urls.
> Do you have any suggestion to how we would type in the multiple urls?
> I'd say `wingetcreate update --multiurl` `C:\manifests\firefox\urls.txt` or `https://github.com/microsoft/edge/urls.txt` and/or csv

I would treat this the same as you would in a PowerShell script. For example, if I wrote a PowerShell script that accepted one or more URL's, I'd make the parameter an array of strings. In this case, accept URLs separated by commas. In the script I would do a foreach $url in $urls. If a person uses the URL parameter with one URL? Then it does one pass. If it passes two or more separated by commas? Then it loops through the URLs for each one passed.

**Comment by palenshus** [comment]
PR out adding support for multiple URLs in new and update commands. This requires that we can determine the correct properties for each package to match it to the previous entry in the manifest, which isn't always the case.

Cases where this breaks down for example:

* x86 installers for x64 apps, for example VLC
* MSIs which don't encode the arch into the MSI DB, for example Edge
* packages which differ by locale only, for example Firefox -- we could eventually try to incorporate this into the matching algorithm, but we can't parse locale from every installerType
* packages which differ by scope only, I don't know how to parse that from the package

For cases like these, and other complex manifests, the user would still just update their manifests manually (or using powershell in their CD pipeline, etc) and use wingetcreate submit
