### ISSUE TITLE
Update Chocolatey Version

### ISSUE THREAD

**Issue by devoptimate** [microsoft/winget-create#534]
### Description of the new feature / enhancement

Our CI pipeline currently commits winget manifests with an outdated manifest version. After investigation it turned out that the most current version committed to the Chocolatey package registry is 1.2.6, while wingetcreate is already released with 1.6.x on scoop and github.

So tr;dr: wingetcreate is not updated anymore on chocolatey unlike it is on winget or scoop

**Comment by mdanish-kh** [comment]
The WinGet team does not maintain the wingetcreate choco package. I believe this issue should be filed over at choco's repo from where the package is being maintained.

I believe it's this repo:
https://github.com/pauby/ChocoPackages/tree/master/automatic/wingetcreate#winget-create

**Comment by devoptimate** [comment]
Alright, thanks, I have submitted the issue there.
