### ISSUE TITLE
Add option to create sources.msix file for private repo

### ISSUE THREAD

**Issue by pquiring** [microsoft/winget-create#537]
### Description of the new feature / enhancement

Would be nice to create my own repo with a simple command.  
Plan to host repo on sourceforge.net (only supports PHP) so I think the REST option is not possible.
Need a new command to create sources.msix for use in private repo.

### Proposed technical implementation details

wingetcreate cache --build --output=folder/path/sources.msix
wingetcreate cache --sign --output=folder/path/sources.msix

**Comment by pquiring** [comment]
I've tried to add "one" package to winget-pkgs and it's taking days.  Once I release and update dozes of packages that would be unacceptable slow :(

**Comment by denelon** [comment]
Building a PreIndexed source should support multiple packages which isn't something wingetcreate was designed to do. As they are MSIX packages, they would also require a certificate for signing. We can keep this issue open here for now, but it may get moved to another project depending on how we decide to implement something like this in the future.

**Comment by pquiring** [comment]
I've created my own repo using the REST API instead.  I'll close this issue.

Thanks!
