### ISSUE TITLE
wingetcreate storing installers in %temp% folder

### ISSUE THREAD

**Issue by KaranKad** [microsoft/winget-create#62]
### Description
When creating new or updating existing manifest, `wingetcreate` is given a download link to the installer so that it can download the application and generate sha256. I've noticed that `wingetcreate` stores the installer in `%temp%` folder after generating sha256. I like this behavior because if I had to do some testing with the installer or get some metadata from it, I would not have to download the installer again. But this could cause storage issue after many submissions so I would like to have a option to clear the installers via the application itself.

### Solution
add some command like `wingetcreate cache clean` to clear the installers.
(optional)
some extra commands like `wingetcreate cache --list` will display all the installers that wingetcreate downloaded. Doesn't have to be exact appname just the installer's name. Output could look similar to when we type `dir` command in a folder. This feature could be easily added if wingetcreate stored installers in it's own directory somewhere instead of `%temp%` folder so that it can just clone what `dir` command does.

**Comment by denelon** [comment]
We may follow the pattern from the Windows Package Manager and use %TEMP%\wingetcreate.

The default behavior may be switched to delete the installer after the hash is calculated unless there is a setting to retain for some period of time.

**Comment by denelon** [comment]
We may follow the pattern from the Windows Package Manager and use %TEMP%\wingetcreate.

The default behavior may be switched to delete the installer after the hash is calculated unless there is a setting to retain for some period of time.
