### ISSUE TITLE
`wingetcreate update` if latest InstallerUrl

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-create#72]
# Description of the new feature/enhancement
`wingetcreate update` should delete the old version folder if it uses the same `InstallerUrl` and count as `Update and Rename` so we or the bot don't have to clean up the folder afterwards.

**Comment by denelon** [comment]
@OfficialEsco do you have an example PR showing what this looks like? I did a quick search and didn't find an example.

**Comment by OfficialEsco** [comment]
That's because you're looking too far https://github.com/microsoft/winget-pkgs/pull/16874/files
This is how it SHOULD look, if you move a few lines it will count as a new file. Wingetbot/WinGetcreate is therefore incompetable with each other.

**Comment by palenshus** [comment]
The latter case is probably due to line endings changing. Anyway, I'm wondering if in cases like this the version shouldn't just be changed to "latest" in the manifest, and that way the directory doesn't change from update to update?

**Comment by OfficialEsco** [comment]
Well wingetbot only updates the hash, I can do a lot bigger changes without the whole file getting recreated...

We have stopped using Latest PackageVersion as it causes issues with winget upgrade.
