### ISSUE TITLE
Adding a "clear cache" command/flag to delete temp files after download

### ISSUE THREAD

**Issue by ryfu-msft** [microsoft/winget-create#92]
After repeated use of the new command, the %temp% directory could be filled with downloaded installers. To resolve this issue, we aim to address this issue by giving users an option to clear out these files.

- Creating a %TEMP%/WingetCreate directory where all downloaded installers will be stored as to not overload the %TEMP% directory.
- Creating a flag/command that clears out all installer files from this directory when executed.

Thanks @KaranKad for coming up with this idea and bringing our attention to this issue #62

**Comment by palenshus** [comment]
Duplicate of #62?
